# Generated by Django 4.2.13 on 2024-07-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='uu_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
