# Generated by Django 4.2.13 on 2024-07-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_movie_description_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Title',
        ),
    ]
