# Generated by Django 4.2.13 on 2024-07-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_rename_title_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
